# Generated by Django 5.0.1 on 2024-03-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('mechanic', 'mechanic')], default='user', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('is_approved', models.CharField(max_length=200)),
                ('specialized_in', models.CharField(choices=[('two_wheeler', 'two_wheeler'), ('four_wheeler', 'four_wheeler'), ('heavy_vehicle', 'heavy_vehicle')], max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='images\\profile_img')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_location', to='ORVBA.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to='ORVBA.user')),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day_rent', models.IntegerField()),
                ('week_rent', models.IntegerField()),
                ('month_rent', models.IntegerField()),
                ('car_img', models.ImageField(null=True, upload_to='images\\car_img')),
                ('discription', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_car_location', to='ORVBA.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('bio', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='images\\profile_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='ORVBA.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReqToMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_location', to='ORVBA.location')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_profile', to='ORVBA.mechanicprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_profile', to='ORVBA.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('total_bill', models.IntegerField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=200)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_mechanicprofile', to='ORVBA.mechanicprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_userprofile', to='ORVBA.userprofile')),
            ],
        ),
    ]
